<a href="https://colab.research.google.com/github/anwesha4002/Anwesha/blob/main/anwesha_samsung_assign.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. Create a 5×5 matrix with values 1,2,3,…,25
mat1 = np.arange(1, 26).reshape(5, 5)
print(mat1)


# 2. Generate a 4×4 identity matrix
iden = np.eye(4)
print(iden)

# 3. 1D array from 100 to 200 with step 10
arr1 = np.arange(100, 201, 10)
print(arr1)

# 4. Random 3×3 matrix and determinant
rand_mat = np.random.rand(3, 3)
det = np.linalg.det(rand_mat)
print(rand_mat, "\nDeterminant:", det)

# 5. Array of 10 random integers between 1 and 100
arr2 = np.random.randint(1, 101, 10)
print(arr2)

# 6. Reshape 1D array of size 12 into 3×4
arr3 = np.arange(12).reshape(3, 4)
print(arr3)

# 7. Matrix multiplication of two 3×3 matrices
a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 3))
print(a @ b)  # or np.dot(a,b)

# 8. Eigenvalues and eigenvectors of a 2×2 matrix
mat2 = np.array([[4, -2], [1, 1]])
eigvals, eigvecs = np.linalg.eig(mat2)
print(eigvals, eigvecs)

# 9. 5×5 matrix with random values and diagonal extraction
rand5 = np.random.rand(5, 5)
print(np.diag(rand5))

# 10. Normalize 1D array
arr4 = np.random.randint(1, 20, 10)
norm_arr = (arr4 - arr4.min()) / (arr4.max() - arr4.min())
print(norm_arr)

# 11. Sort array by row and column
mat3 = np.random.randint(1, 50, (4, 4))
print("Row-wise:\n", np.sort(mat3, axis=1))
print("Column-wise:\n", np.sort(mat3, axis=0))

# 12. Indices of max and min
arr5 = np.random.randint(1, 100, 10)
print(np.argmax(arr5), np.argmin(arr5))

# 13. Flatten 2D array
mat4 = np.arange(12).reshape(3, 4)
print(mat4.ravel(), mat4.flatten())

# 14. Inverse of 3×3 matrix
mat5 = np.random.randint(1, 10, (3, 3))
print(np.linalg.inv(mat5))

# 15. Random permutation of numbers 1 to 10
print(np.random.permutation(np.arange(1, 11)))

# 16. Replace even numbers with -1
arr6 = np.arange(21)
arr6[arr6 % 2 == 0] = -1
print(arr6)

# 17. Dot product of two arrays
a1, a2 = np.array([1, 2, 3]), np.array([4, 5, 6])
print(np.dot(a1, a2))

# 18. Trace of 5×5 random matrix
mat6 = np.random.randint(1, 10, (5, 5))
print(np.trace(mat6))

# 19. Split 1D array into 3 equal parts
arr7 = np.arange(9)
print(np.split(arr7, 3))

# 20. 3D array (3,3,3) mean across axis=0
arr8 = np.random.rand(3, 3, 3)
print(arr8.mean(axis=0))

# 21. Cumulative sum
arr9 = np.arange(10)
print(np.cumsum(arr9))

# 22. Extract upper triangular matrix
mat7 = np.random.randint(1, 10, (4, 4))
print(np.triu(mat7))

# 23. 6×6 checkerboard pattern
checker = np.indices((6, 6)).sum(axis=0) % 2
print(checker)

# 24. Element-wise sqrt of 3×3 matrix
mat8 = np.random.randint(1, 10, (3, 3))
print(np.sqrt(mat8))

# 25. Reverse 1D array (no slicing)
arr10 = np.arange(20)
print(np.flip(arr10))

# 26. Merge two arrays vertically & horizontally
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(np.vstack((x, y)))
print(np.hstack((x, y)))

# 27. Row-wise and column-wise sum
mat9 = np.arange(12).reshape(3, 4)
print(mat9.sum(axis=1), mat9.sum(axis=0))

# 28. Replace NaN with column mean
arr11 = np.array([[1, np.nan, 3], [4, 5, np.nan]])
col_mean = np.nanmean(arr11, axis=0)
inds = np.where(np.isnan(arr11))
arr11[inds] = np.take(col_mean, inds[1])
print(arr11)

# 29. Cosine similarity
u, v = np.random.rand(5), np.random.rand(5)
cos_sim = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))
print(cos_sim)

# 30. Rotate 4×4 array by 90 degrees
mat10 = np.arange(16).reshape(4, 4)
print(np.rot90(mat10))

# 31. Structured array with fields (name, age, marks)
data = np.array([("Alice", 21, 85.5), ("Bob", 22, 90.1)],
                dtype=[("name", "U10"), ("age", "i4"), ("marks", "f4")])
print(data)

# 32. Rank of 3×3 random matrix
mat11 = np.random.rand(3, 3)
print(np.linalg.matrix_rank(mat11))

# 33. Normalize each row (unit length)
mat12 = np.random.rand(5, 5)
row_norms = np.linalg.norm(mat12, axis=1, keepdims=True)
print(mat12 / row_norms)

# 34. Check if arrays are equal element-wise
print(np.array_equal([1, 2, 3], [1, 2, 3]))

# 35. Histogram of dataset
dataset = np.random.randn(1000)
hist, bins = np.histogram(dataset, bins=10)
print(hist, bins)

# 36. Broadcasting addition
A = np.ones((3, 3))
b = np.array([1, 2, 3])
print(A + b)

# 37. Unique values and counts
arr12 = np.random.randint(1, 10, 20)
uniq, counts = np.unique(arr12, return_counts=True)
print(uniq, counts)

# 38. Pearson correlation coefficient
x = np.random.rand(10)
y = np.random.rand(10)
print(np.corrcoef(x, y)[0, 1])

# 39. Numerical gradient of 1D array
arr13 = np.array([1, 2, 4, 7, 11, 16])
print(np.gradient(arr13))

# 40. SVD of random 3×3 matrix
mat13 = np.random.rand(3, 3)
U, S, Vt = np.linalg.svd(mat13)
print("U:\n", U, "\nS:\n", S, "\nVt:\n", Vt)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[100 110 120 130 140 150 160 170 180 190 200]
[[0.03726467 0.85968866 0.80415042]
 [0.99729549 0.04378751 0.20495637]
 [0.90789154 0.4421055  0.56531877]] 
Determinant: -0.004579284750610426
[38 10 16 69 61 20 16 94 83  4]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[166  66  98]
 [200  74 113]
 [100  30  53]]
[3. 2.] [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
[0.50204506 0.1243038  0.9158449  0.45462105 0.64069404]
[0.82352941 0.29411765 0.76470588 0.58823529 0.11764706 0.
 0.58823529 0.82352941 1.         0.94117647]
Row-wise:
 [[17 24 25 41]
 [ 4 11 38 43]
 [11 12 24 49]
 [11 14 41 43]]
Column-wise:
 [[ 4 38 11 11]
 [11 41 24 14]
 [12 41 43 24]
 [17 49 43 25]]
5 8
[ 0  1  2  3  4  5  6  7  8  9 10 11] [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0.25806452  0.07373272 -0.11520737]
 [-0.03225806 -0.15207373  0.17511521]
 [-0.19